Repository greatSumini/pickk-app, pull requests merged in 2020-07, with the labels that each got.

#39 [Feature] add swr modules
  config/index.ts
  package-lock.json
  package.json
  src/components/post-list/index.tsx
  src/hooks/api/useRequest.ts
  src/modules/list/list-props.d.ts
  src/modules/list/scroll.tsx
  src/services/Api.ts
  src/services/Review/config.ts
  src/services/Review/index.ts
  src/types/Api.ts
  src/types/Auth.ts
  src/types/Brand.ts
  src/types/Cart.ts
  src/types/Comment.ts
  src/types/Item.ts
  src/types/ItemStore.ts
  src/types/ItemType.ts
  src/types/Order.ts
  src/types/OrderItem.ts
  src/types/OrderSheet.ts
  src/types/Payment.ts
  src/types/Post.ts
  src/types/Question.ts
  src/types/ShopDrawer.ts
  src/types/User.ts
  src/types/index.ts
Labels: implement

#41 [Feature] add app context
  ios/PickkApp.xcworkspace/contents.xcworkspacedata
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/app.tsx
  src/components/splash/index.tsx
  src/context/app.tsx
  src/modules/navigation/navigator/index.tsx
  src/services/Api.ts
  src/services/User/config.ts
  src/services/User/index.ts
Labels: implement

#43 [Enhance] add post card wide review
  ios/PickkApp.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
  src/assets/icons/icons.d.ts
  src/assets/icons/item/Partner.tsx
  src/components/channel/index.tsx
  src/components/post-list/card/wide/card-thumbnail/index.tsx
  src/components/post-list/card/wide/card-thumbnail/props.d.ts
  src/components/post-list/card/wide/footer/index.tsx
  src/components/post-list/card/wide/footer/props.d.ts
  src/components/post-list/card/wide/header/index.tsx
  src/components/post-list/card/wide/header/props.d.ts
  src/components/post-list/card/wide/index.tsx
  src/components/post-list/card/wide/item-row/props.d.ts
  src/components/post-list/card/wide/props.d.ts
  src/components/post-list/card/wide/review/header.tsx
  src/components/post-list/card/wide/review/index.tsx
  src/components/post-list/card/wide/review/item-row.tsx
  src/components/post-list/card/wide/review/thumbnail.tsx
  src/components/post-list/index.tsx
  src/components/post-list/props.d.ts
  src/components/splash/index.tsx
  src/lib/utils/image-size-parser.ts
  src/lib/utils/time-parser.ts
  src/lib/utils/url-parser.ts
  src/modules/atoms/img.tsx
  src/modules/list/list-props.d.ts
  src/modules/list/scroll.tsx
  src/modules/molecules/button/profile-node.tsx
Labels: enhancement

#45 [Feature] add skeleton
  package-lock.json
  package.json
  src/components/post-list/card/wide/review/item-row.tsx
  src/components/post-list/index.tsx
  src/modules/skeletons/post/post-card.tsx
Labels: implement

#49 [Feature] Add orderitem service
  src/services/OrderItem/config.ts
  src/services/OrderItem/index.ts
Labels: feature

#51 [Feature] Add backheader module
  src/assets/icons/arrow/left.tsx
  src/assets/icons/logo/index.tsx
  src/constants/colors.tsx
  src/modules/molecules/header/back.tsx
Labels: feature

#53 [Feature] Add orders page,components
  config/index.ts
  ios/PickkApp.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/components/my/index.tsx
  src/components/order-list/footer/content.tsx
  src/components/order-list/footer/index.tsx
  src/components/order-list/index.tsx
  src/components/order-list/item/card.tsx
  src/components/order-list/item/description.tsx
  src/components/order-list/item/footer.tsx
  src/components/order-list/item/header.tsx
  src/components/order-list/item/index.tsx
  src/components/search/index.tsx
  src/components/search/no-result/index.tsx
  src/lib/utils/date-parser.ts
  src/lib/utils/number-parser.ts
  src/modules/atoms/col.tsx
  src/modules/atoms/index.ts
  src/modules/atoms/row.tsx
  src/modules/list/list-props.d.ts
  src/modules/list/scroll.tsx
  src/modules/molecules/header/back.tsx
  src/modules/molecules/no-result.tsx
  src/modules/navigation/navigator/stacks/app.tsx
  src/services/OrderItem/config.ts
  src/services/OrderItem/index.ts
  src/types/OrderItem.ts
Labels: feature

#54 [Feature] add kakao login
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  ios/PickkApp.xcodeproj/project.pbxproj
  ios/PickkApp/AppDelegate.m
  ios/PickkApp/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/login/index.tsx
  src/components/login/kakao-login.tsx
  src/components/my/index.tsx
  src/components/my/props.d.ts
  src/modules/navigation/navigator/stacks/app.tsx
Labels: feature

#57 [Feature] add apple login
  ios/PickkApp.xcodeproj/project.pbxproj
  ios/PickkApp/PickkApp.entitlements
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/login/apple-login-button.tsx
  src/components/login/index.tsx
  src/components/login/kakao-login-button.tsx
  src/interfaces/User/IItemPoints.ts
  src/interfaces/User/IPoint.ts
  src/interfaces/User/IUser.ts
  src/services/Auth/config.ts
  src/services/Auth/index.ts
  src/services/User/config.ts
  src/services/User/index.ts
  src/types/Auth.ts
  src/types/User.ts
Labels: feature

#58 [Feature] add facebook login
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/pickkapp/MainApplication.java
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  ios/Dummy.swift
  ios/PickkApp-Bridging-Header.h
  ios/PickkApp.xcodeproj/project.pbxproj
  ios/PickkApp/AppDelegate.m
  ios/PickkApp/Info.plist
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/login/facebook-login-button.tsx
  src/components/login/index.tsx
Labels: feature

#62 [Feature] add molecules section
  src/assets/icons/chevron/right.tsx
  src/components/home/index.tsx
  src/modules/atoms/touchable.tsx
  src/modules/molecules/section.tsx
Labels: feature

#64 [Feature] add atoms/LabeledComponent
  src/modules/atoms/index.ts
  src/modules/atoms/labeled-component.tsx
Labels: feature

#65 [Feature] add order screen
  src/components/order-list/footer/index.tsx
  src/components/order-list/index.tsx
  src/components/order-list/item/card.tsx
  src/components/order-list/item/description.tsx
  src/components/order-list/item/footer.tsx
  src/components/order-list/item/header.tsx
  src/components/order-list/item/index.tsx
  src/components/order/index.tsx
  src/components/order/item-list/brand-header.tsx
  src/components/order/item-list/index.tsx
  src/components/post-list/card/wide/review/index.tsx
  src/hooks/Order.ts
  src/hooks/index.ts
  src/interfaces/Item/IItem.ts
  src/interfaces/Order/IOrder.ts
  src/lib/utils/PhoneNumberParser.ts
  src/lib/utils/index.ts
  src/lib/utils/price-parser.ts
  src/modules/atoms/index.ts
  src/modules/atoms/labeled-component.tsx
  src/modules/atoms/labeled.tsx
  src/modules/molecules/section.tsx
  src/modules/navigation/navigator/stacks/app.tsx
  src/services/Order/config.ts
  src/services/Order/index.ts
  src/types/OrderItem.ts
Labels: feature

#67 [Feature] Add order cancel screen
  package-lock.json
  package.json
  src/assets/icons/check.tsx
  src/assets/icons/receipt.tsx
  src/assets/icons/x.tsx
  src/components/order-cancel/index.tsx
  src/components/order-cancel/product/brand-card.tsx
  src/components/order-cancel/product/card.tsx
  src/components/order-cancel/product/description.tsx
  src/components/order-cancel/product/list.tsx
  src/components/order-claim/complete.tsx
  src/components/order-claim/footer.tsx
  src/components/order-claim/header.tsx
  src/components/order-claim/reason.tsx
  src/components/order-list/item/footer.tsx
  src/context/cancel.tsx
  src/hooks/Order.ts
  src/modules/molecules/button/check.tsx
  src/modules/molecules/header/title.tsx
  src/modules/molecules/section.tsx
  src/modules/navigation/navigator/stacks/app.tsx
  src/services/Order/config.ts
  src/services/Order/index.ts
Labels: feature

#71 [Feature] Add order exchange page
  package-lock.json
  package.json
  src/assets/icons/chevron/down.tsx
  src/assets/icons/icons.d.ts
  src/components/my/index.tsx
  src/components/order-cancel/index.tsx
  src/components/order-cancel/product/list.tsx
  src/components/order-claim/complete.tsx
  src/components/order-claim/footer.tsx
  src/components/order-claim/header.tsx
  src/components/order-claim/progress/bar.tsx
  src/components/order-claim/progress/node.tsx
  src/components/order-claim/reason.tsx
  src/components/order-claim/sent-checker.tsx
  src/components/order-claim/tracking-code.tsx
  src/components/order-exchange/index.tsx
  src/components/order-exchange/phase0/index.tsx
  src/components/order-exchange/phase0/option-select.tsx
  src/components/order-exchange/phase0/product-card.tsx
  src/components/order-exchange/phase1/exchange-policy.tsx
  src/components/order-exchange/phase1/index.tsx
  src/components/order-exchange/phase1/product-card.tsx
  src/components/order-list/item/description.tsx
  src/components/order-list/item/footer.tsx
  src/components/order-list/item/index.tsx
  src/context/cancel.tsx
  src/hooks/Item.ts
  src/hooks/OrderItem.ts
  src/lib/utils/index.ts
  src/modules/atoms/picker.tsx
  src/modules/navigation/navigator/stacks/app.tsx
  src/services/Item/config.ts
  src/services/Item/index.ts
  src/services/Order/index.ts
  src/services/OrderItem/config.ts
  src/services/OrderItem/index.ts
  src/types/OrderItem.ts
Labels: feature

#73 [Enhance] Apply design system to atom button. Change button design of order-cancel, order-exchange
  src/components/order-claim/footer.tsx
  src/components/order-list/item/footer.tsx
  src/modules/atoms/button.tsx
Labels: enhancement

#78 [Feature] Add my questions screen
  src/assets/icons/inquiry.tsx
  src/assets/icons/secret.tsx
  src/components/my-question-list/card/description.tsx
  src/components/my-question-list/card/index.tsx
  src/components/my-question-list/date-header.tsx
  src/components/my-question-list/index.tsx
  src/components/my/index.tsx
  src/components/order-cancel/product/card/description.tsx
  src/components/order-cancel/product/card/index.tsx
  src/components/order-cancel/product/info.tsx
  src/components/order-exchange/index.tsx
  src/components/order-exchange/phase1/exchange-policy.tsx
  src/components/order-refund/phase1/refund-policy.tsx
  src/context/refund.tsx
  src/hooks/index.ts
  src/hooks/question.ts
  src/modules/navigation/navigator/stacks/app.tsx
  src/services/Question/config.ts
  src/services/Question/index.ts
Labels: feature

#80 [Feature] Add question detail screen
  src/components/my-question-list/card/index.tsx
  src/components/question-detail/card/answer.tsx
  src/components/question-detail/card/item.tsx
  src/components/question-detail/card/question.tsx
  src/components/question-detail/index.tsx
  src/hooks/question.ts
  src/modules/navigation/navigator/stacks/app.tsx
  src/services/Question/config.ts
  src/services/Question/index.ts
Labels: feature

#82 [Feature] add store context
  package-lock.json
  package.json
  src/app.tsx
  src/components/order/index.tsx
  src/components/splash/index.tsx
  src/context/app.tsx
  src/context/store/IStoreContext.ts
  src/context/store/index.tsx
  src/modules/navigation/navigator/index.tsx
  src/types/ItemStore.ts
  src/types/Post.ts
  src/types/ShopDrawer.ts
Labels: feature
